### ISSUE TITLE
Getting error when running testsuite

### ISSUE THREAD

**Issue by Leuug** [getting-things-gnome/liblarch#26]
I'm trying to package `liblarch` to fedora and I'm getting the following error message during the test:
```bash
+ ./run-tests
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
..
(run-tests:177): Gtk-CRITICAL **: 16:54:23.037: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(run-tests:177): Gtk-CRITICAL **: 16:54:23.037: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(run-tests:177): Gtk-CRITICAL **: 16:54:23.037: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
/var/tmp/rpm-tmp.3ij6TJ: line 32:   177 Segmentation fault      (core dumped) ./run-tests
error: Bad exit status from /var/tmp/rpm-tmp.3ij6TJ (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.3ij6TJ (%check)
```
I am using `python3-nose`, `python3-pyflakes`, `python3-spec`, `python3-pycodestyle`, `python3-gobject` and `gtk3` as build dependencies. I think there is some other dependency to the test-suite that is missing but I didn't found what packages are necessary  to run the test anywhere on the repo.

**Comment by ploum** [comment]
Really strange. I can’t reproduce this on Ubuntu. 

To me, it doesn’t look like a missing dependancy but a bug in GTK. Are you using the latest GTK3 libraries ?

**Comment by Leuug** [comment]
I'm using "mock" to build the RPM. I read an old liblarch spec file and it seems to be related to tests that require a display, and when it can't connect it gives an error. So I guess it's not about the tests, it's about how "mock" works.

I think this issue can be closed, but I would like to know what are the build dependencies and what are the runtime dependencies, it's not very clear to me.

**Comment by ploum** [comment]
It’s Python so runtime = buildtime. Dependencies are the same.
