### ISSUE TITLE
LGPLv3-only or LGPLv3-or-later

### ISSUE THREAD

**Issue by Leuug** [getting-things-gnome/liblarch#27]
In the README it says that the project is licensed under LGPLv3, I would like to know if it is `LGPLv3-only` or `LGPLv3-or-later`.

In the headers of the source code it says `LGPLv3 or any later version`, but on Github and in the LICENSE file it just says `LGPLv3`.

**Comment by ploum** [comment]
I created liblarch and I really don’t care. Assume the more liberal case which is -or-later.

Contribution to modiying the LICENSE file will be gladly accepted.

**Comment by Leuug** [comment]
Closed by #28
