### ISSUE TITLE
Cleanup debian packaging and upload new version to debian archive

### ISSUE THREAD

**Issue by ao2** [getting-things-gnome/liblarch#31]
Hi,

I was looking into updating the gtg package in debian and I noticed that liblarch is also a gtg dependency.

I see that there is a `debian/` dir in the repository and it looks like it is in a fairly decent shape (thanks), however there are still a couple of details that would prevent the upload in the debian archive.

For example, the "*usual*" workflow for packaging sources hosted in git repository using a `3.0 (Quilt)` source format is to have the `debian/` dir in a separate branch, so that an `.orig.tgz` can be easily created from the upstream branch.

Would you be opened to create a `debian/master` branch to separately track the debian packaging bits?

Thanks, Antonio

**Comment by ploum** [comment]
Hello,

I will happily merge any PR that could help Debian packaging. I’m sad of gtg not being in Debian anymore.

Unfortunately, I’m really bad at Debian packaging so I can’t really do anything myself but accept merge requests related to that, for both liblarch and gtg.

**Comment by ploum** [comment]
I feel that this bug has been addressed as liblarch is now in Debian
