### ISSUE TITLE
installation of GTG

### ISSUE THREAD

**Issue by Shahin-rmz** [getting-things-gnome/liblarch#33]
Hello,
I have recently tried out to run GTG via .launch command.
I got the following error.
![image](https://user-images.githubusercontent.com/32805117/150529072-df3ca09a-b8ff-4cfa-bee1-5d9ec851ac27.png)

after trying to install liblarch, I get following massage.
![image](https://user-images.githubusercontent.com/32805117/150529023-e35f2d52-ae07-4ca6-85ea-1377e6547bb3.png)
why the python still does not recognize the liblarch?
what is the issue?

**Comment by ploum** [comment]
did you install liblarch ?

**Comment by Shahin-rmz** [comment]
I could,
But the GTG does not recognize it.
(sadly)

**Comment by ploum** [comment]
The error tells that liblarch is not installed correctly on your system.  (to test, you could simply type "python" then "import liblarch_gtk")

see https://wiki.gnome.org/Projects/liblarch/installation

**Comment by diegogangl** [comment]
@Shahin-rmz Try the following
`pip3 install --user -e git+https://github.com/getting-things-gnome/liblarch.git#egg=liblarch`

**Comment by Shahin-rmz** [comment]
Thanks @ploum @diegogangl 
I will do it, (but not today because of plans) and update you about the results. 
Thanks again.

**Comment by Shahin-rmz** [comment]
> Try the following 
thanks you.
With your help I could manage to install the library and open the application.
