### ISSUE TITLE
Uses unmaintained dependency Nose

### ISSUE THREAD

**Issue by mzf-guest** [getting-things-gnome/liblarch#35]
Dear liblarch developers,

this software uses nose, which is an obsolete testing framework, [unmaintained](https://github.com/nose-devs/nose/commit/0f40fa995384afad) since [2015](https://pypi.org/project/nose/#history).

Do you have any plan to migrate to another testing framework like Nose2, pytest or unittest?

This was discussed on the liblarch Debian Package bug tracker:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018398

Thanks!

**Comment by Neui** [comment]
Related on the GTG side: https://github.com/getting-things-gnome/gtg/issues/773
